version: "2.1"
services:
  github-webhook:
    restart: unless-stopped
    image: staticfloat/docker-webhook
    volumes:
      # Mount this code into /code
      - ./:/code
      # Mount the docker socket
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - WEBHOOK_HOOKS_DIR=/code/hooks
      - WEBHOOK_BRANCH_LIST=master
    expose:
      - 8000
